### ISSUE TITLE
Pure 64-bit and please leave binary out

### ISSUE THREAD

**Issue by livibetter** [nedearb/Underneath#25]
Firstly, the **32/64-bit**

I use Linux, pure 64-bit, no 32-bit stuff on my system, so Underneath failed to build, so I commented out the `-m32` and it has no problems to build (both ncurses and SDL) and seems to run normally. I don't know much about GCC, but I don't think you need that flag, GCC should be able to detect on its own for the architecture. If it's Windows issue, which I don't know if 64-bit libraries are available, but it's been so many years, they can't still be missing 64-bit build.

Secondly, the **binary in repository**

Please remove them from Git completely. As of now, 275MB for the clone, even GitHub is fast, still takes time when the pure source only take a few seconds to clone. In a few years, you will cross [the quota][quota]. There is not much point or use to have binary builds in repository, when people who clone are most likely to have the ability to build, especially like the 32/64 issue I have, the included binary can't even be run on my system

[quota]: https://help.github.com/articles/what-is-my-disk-quota/

Build release package/tarball/archive when it's time to make a release, then use Release for uploading the file. That's the one should include the binary builds.

Now since no one has yet to fork your repo, you can safely remove those from your commit history.

**Comment by nedearb** [comment]
Oh wow, I had no idea anyone had ever seen my project. I'm flattered you've taken time to give me some constructive criticism. I recently changed the build script to not automatically add the ```-m32``` flag as I had just tried it on my Linux system and encountered the same issue (I usually work on my Macbook so I didn't think about that issue).

As for the binaries in the repo, I hadn't considered clone speed or the quota. I really appreciate bringing this to my attention. I originally did it so my friends could easily download them, but I should definitely move them away from the repository. 

I'm also going to remove the android port, this was not designed for android...
